name: KopisEnginePython
options:
  bundleIdPrefix: com.kopisengine.python
  deploymentTarget:
    macOS: "13.0"
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  disableBundleVersioning: false

configs:
  Debug:
    CODE_SIGNING_REQUIRED: false
    CODE_SIGNING_ALLOWED: true
    CODE_SIGN_IDENTITY: "-"
  Release:
    CODE_SIGNING_REQUIRED: false
    CODE_SIGNING_ALLOWED: true
    CODE_SIGN_IDENTITY: "-"

packages:
  PythonKit:
    url: https://github.com/pvieito/PythonKit.git
    branch: master

targets:
  KopisEnginePython:
    type: tool
    platform: macOS
    sources:
      - path: Sources/KopisEnginePythonRunner
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kopisengine.python.KopisEnginePython
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      SWIFT_VERSION: "5.9"
      PRODUCT_NAME: KopisEnginePython
      # Set project root path for Python script location
      PROJECT_ROOT: $(SRCROOT)/..

  KopisEngineiOS:
    type: application
    platform: iOS
    sources:
      - path: Sources/KopisEngineiOS
    dependencies:
      - package: PythonKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kopisengine.python.KopisEngineiOS
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      SWIFT_VERSION: "5.9"
      PRODUCT_NAME: KopisEngineiOS
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: Info-iOS.plist
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      CODE_SIGNING_REQUIRED: true
      CODE_SIGNING_ALLOWED: true
    info:
      path: Info-iOS.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: ["armv7"]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

schemes:
  KopisEnginePython:
    build:
      targets:
        KopisEnginePython: all
    run:
      config: Debug
      executable: KopisEnginePython
      arguments:
        environmentVariables:
          PROJECT_ROOT: $(SRCROOT)/..
      workingDirectory: $(SRCROOT)/..

  KopisEngineiOS:
    build:
      targets:
        KopisEngineiOS: all
    run:
      config: Debug
      executable: KopisEngineiOS
      launchArguments: []
