name: KopisEngine
options:
  bundleIdPrefix: com.kopisengine
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  disableBundleVersioning: false

configs:
  Debug:
    CODE_SIGNING_REQUIRED: false
    CODE_SIGNING_ALLOWED: true
    CODE_SIGN_IDENTITY: "-"
  Release:
    CODE_SIGNING_REQUIRED: false
    CODE_SIGNING_ALLOWED: true
    CODE_SIGN_IDENTITY: "-"

packages:
  KopisEngine:
    path: .

targets:
  KopisEngine:
    type: framework
    platform: macOS
    sources:
      - path: Sources/KopisEngine
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kopisengine.KopisEngine
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"

  KopisEngineApp:
    type: tool
    platform: macOS
    sources:
      - path: Sources/KopisEngineApp
    dependencies:
      - target: KopisEngine
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kopisengine.KopisEngineApp
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"

  KopisEngineGUI:
    type: application
    platform: macOS
    sources:
      - path: Sources/KopisEngineGUI
        compilerFlags:
          - -fcxx-modules
    dependencies:
      - target: KopisEngine
    frameworks:
      - CoreGraphics
      - CoreVideo
      - QuartzCore
      - SwiftUI
      - AppKit
      - Metal
      - MetalKit
      - AVFoundation
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kopisengine.KopisEngineGUI
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      INFOPLIST_FILE: Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: ""
      CODE_SIGN_ENTITLEMENTS: ""
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ENABLE_HARDENED_RUNTIME: NO
      CODE_SIGNING_REQUIRED: false
      CODE_SIGNING_ALLOWED: true
      GENERATE_INFOPLIST_FILE: NO
      # Metal 4 settings (MSL 2.4+)
      METAL_CPP: YES
      METAL_LANGUAGE_VERSION: "2.4"
      METAL_SHADER_DEBUG_INFO: YES
      METAL_SHADER_VALIDATION: YES
      # C++ settings for Metal interop
      CLANG_CXX_LANGUAGE_STANDARD: "c++17"
      CLANG_CXX_LIBRARY: "libc++"
      # Optimization for Debug builds
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      GCC_OPTIMIZATION_LEVEL: 0
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "13.0"
        NSHumanReadableCopyright: ""
        NSHighResolutionCapable: true
        NSSupportsAutomaticGraphicsSwitching: true

schemes:
  KopisEngine:
    build:
      targets:
        KopisEngine: all
    run:
      config: Debug

  KopisEngineApp:
    build:
      targets:
        KopisEngine: all
        KopisEngineApp: all
    run:
      config: Debug
      executable: KopisEngineApp

  KopisEngineGUI:
    build:
      targets:
        KopisEngine: all
        KopisEngineGUI: all
    run:
      config: Debug
      executable: KopisEngineGUI

